# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Promoskop' do

end

platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'SDWebImage', '~>3.7.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'SWRevealViewController', '~>2.3.0'
pod 'Colours'
pod 'AFNetworkActivityLogger'
pod 'iRate'
pod 'pop'
pod 'CrittercismSDK'

target 'PromoskopTests' do

end

